/**
 * registry-files.ts — the one place that decides which files under
 * `src/registry/components/<slug>/` ship to consumers, and under what path.
 *
 * Two outputs are built from this list and must never disagree:
 *   - the shadcn `registry:component` JSON in `public/r/<slug>.json`
 *   - `src/registry/sources.generated.ts`, which embeds the same files into
 *     the AI prompt so a component can be reproduced byte-for-byte without
 *     the CLI
 *
 * Node-only (reads the filesystem); imported by the generator script and
 * the drift test, never by app code.
 */
import * as fs from "node:fs";
import * as path from "node:path";

export type RegistryFile = {
  /** Consumer-side path, relative to the components alias root. */
  path: string;
  type: "registry:component" | "registry:file";
  target: string;
  content: string;
};

/**
 * Maps the files on disk under `componentsDir/<slug>/` to shadcn `files[]`
 * entries. The single `.tsx` ships as `index.tsx` so the folder import
 * `@/components/<slug>` works; anything else (e.g. the CSS module) ships
 * verbatim as `registry:file` pinned to the same folder via `target`.
 * `index.ts` (the in-repo re-export) is not shipped.
 *
 * Every file gets an explicit `target`. The CLI only maps `path` to a
 * subfolder when its alias-root matching (Kc) sees a POSIX separator — on
 * Windows the resolved path keeps backslashes, the match fails, and the
 * file collapses to a bare filename under `src/components/`. An explicit
 * `target` bypasses that entirely.
 */
export function registryFiles(componentsDir: string, slug: string): RegistryFile[] {
  const dir = path.join(componentsDir, slug);
  const files = fs
    .readdirSync(dir)
    .filter((file) => file !== "index.ts")
    .sort();

  const tsx = files.filter((file) => file.endsWith(".tsx"));
  if (tsx.length !== 1) {
    throw new Error(
      `[${slug}] expected exactly one .tsx in ${dir}, found ${tsx.length} (${files.join(", ")})`,
    );
  }
  const main = tsx[0];

  // Main file first: it is what a reader (or an AI assistant) looks at
  // before the stylesheet, and the registry JSON keeps the same order.
  const ordered = [main, ...files.filter((file) => file !== main)];

  return ordered.map((file) => {
    const content = fs.readFileSync(path.join(dir, file), "utf8");
    if (file === main) {
      return {
        path: `components/${slug}/index.tsx`,
        type: "registry:component",
        target: `@components/${slug}/index.tsx`,
        content,
      };
    }
    return {
      path: `components/${slug}/${file}`,
      type: "registry:file",
      target: `@components/${slug}/${file}`,
      content,
    };
  });
}

/**
 * Renders `src/registry/sources.generated.ts`: the shipped files of every
 * component as string constants, keyed by slug. JSON.stringify keeps the
 * contents byte-exact (the AI prompt embeds them verbatim).
 */
export function renderSourcesModule(
  sources: Record<string, RegistryFile[]>,
): string {
  const entries = Object.entries(sources)
    .map(([slug, files]) => {
      const list = files
        .map(
          (file) =>
            `    {\n      path: ${JSON.stringify(file.path)},\n      content: ${JSON.stringify(file.content)},\n    },`,
        )
        .join("\n");
      return `  ${JSON.stringify(slug)}: [\n${list}\n  ],`;
    })
    .join("\n");

  return `// AUTO-GENERATED by scripts/generate-registry.ts — do not edit by hand.
// Regenerate with \`npm run registry:build\` (also runs on \`npm run dev\` and
// \`npm run build\`). tests/sources.test.ts fails when this file is stale.
import type { RegistrySourceFile } from "./sources";

export const registrySources: Record<string, RegistrySourceFile[]> = {
${entries}
};
`;
}
